### ISSUE TITLE
Some Thoughts - relating to SkriptHub docs & this addon

### ISSUE THREAD

**Issue by Setloth** [scraft-official/skScraft#1]
This isn't a bug or anything just a little suggestion

1. Your syntaxes on SkriptHub are hoisted, the (1.3) at the beginning of them is pushing them to the very top of the page. This is kind of annoying. I'm not 100% sure what the 1.3 is because the addon version provided is different.
2. You do not have to list every single Minecraft version your syntax works for, in reality, you really don't even need to provide it but if you do its much easier and visibly accepted to do X.x + as in **1.9+** rather than **1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15, 1.16+**.

Lastly, again this is just my opinion, take my advice or not, that is up to you.

~ All being said, have a good day.

**Comment by scraft-official** [comment]
_Hello,
Thank you very much for this report,_ 

 1. I have added prefix (1.3) to show the current version of skScraft addon, and i didn't notice that my addon have been pusshed to the top of skriptHUB docs. I will remove this prefix, to make the docs cleaner. That wasn't planned. Sorry for this issue.
 2. Thank you for this suggestion, i will provide a little update on the supported versions, and set them as you said.

 _Best regards,
 scraft_
