### ISSUE TITLE
Execute console commands.

### ISSUE THREAD

**Issue by baylorhenshaw** [scraft-official/skScraft#2]
Hello, I have been messing with this for a while today. I wanted to ask for a few features if that is okay. If it's even possible, would you add and `execute console command "command" on server "server"` effect? Thanks!

**Comment by scraft-official** [comment]
Hi,
Thank you for your proposition, I think that is the really missing feature for now, so i will try to implement it, I'm working on version 1.4, so in few days i will try to update this reasource, i have a lot of work at school for now, this is why i have stopped updating this resource, but when i will have a moment free, I will go on and finish the version 1.4.
Best regards,
Scraft
