### ISSUE TITLE
Incredibly laggy.

### ISSUE THREAD

**Issue by baylorhenshaw** [scraft-official/skScraft#3]
I want to open another issue to report an actual issue. When you try to make a lot of requests (like 20 at a time), the server tps drops a ton! Even when trying to add delays to optimize the code, it still is slow. I think that this is because it isn't asynchronous.

This is the tps after multiple requests for the whole network info.
![Screen Shot 2021-02-03 at 8 50 00 AM](https://user-images.githubusercontent.com/64096464/106763791-cec34600-65fc-11eb-94fd-13cf105dff66.png)
![Screen Shot 2021-02-03 at 8 51 00 AM](https://user-images.githubusercontent.com/64096464/106763932-f1555f00-65fc-11eb-98c4-39fd0f4581e5.png)

This is my tps and mspt normally when it tries to grab information to stay updated.
![Screen Shot 2021-02-03 at 8 47 57 AM](https://user-images.githubusercontent.com/64096464/106763492-8441c980-65fc-11eb-8d90-5484795709c3.png)
![Screen Shot 2021-02-03 at 8 48 17 AM](https://user-images.githubusercontent.com/64096464/106763546-902d8b80-65fc-11eb-842d-cb2111b897df.png)

Edit: This is the info I'm grabbing to cause the screen shots above!
![Screen Shot 2021-02-03 at 8 54 06 AM](https://user-images.githubusercontent.com/64096464/106764408-60cb4e80-65fd-11eb-9d51-5825ce28b014.png)

**Comment by scraft-official** [comment]
Hi,
Thank you for your report! When I was coding this plugin, it's true that i didn't made any async tasks in skScraft because the BungeeBridge API already have implemented it. During stress tests of effects and expressions, there were no problem with lag spikes or tps drop, if you can post your skript for me to try by my self to remake your issue, I will try to implement the async tasks in the future releases. If you can add too your /timings, it will help me to find the main problem.
Best regards,
Scraft

**Comment by scraft-official** [comment]
Also if you can send me the information about the connection of BungeeBride between subserver and BungeeCord. The information can be found when BungeeBridge is loading, it looks like that:
![image](https://user-images.githubusercontent.com/63715927/106792845-f810c000-6656-11eb-889d-4f572a523af5.png)

**Comment by baylorhenshaw** [comment]
`Connected! Server ---[109ms]---> Bungee ---[3ms]---> Server`
and the command code
```
# Network Information
command /networkinfo [<text>]:
	aliases: /netinfo
	trigger:
		send "{@prefix} {@color-1}Grabbing Information..." to player
		set {_servers::*} to {@server-list}
		set {_offline} to 0
		set {_online} to 0
		loop {_servers::*}:
			if server loop-value is online:
				add 1 to {_online}
				set {_servers::%loop-value%::players} to number of players on server loop-value
				set {_servers::%loop-value%::online} to true
			else:
				add 1 to {_offline}
				set {_servers::%loop-value%::players} to 0
				set {_servers::%loop-value%::online} to false


		send "&8&m                               " to player
		send "{@color-3}Network Information:" to player
		send "&8• {@color-1}Total Players: {@color-2}%number of players on network%" to player
		send "&8• {@color-1}Online Servers: &f%{_online}%" to player
		send "&8• {@color-1}Offline Servers: &f%{_offline}%" to player
		send "{@color-3}Servers:" to player
		loop {_servers::*}:
			{_servers::%loop-value%::online} is true
			if {_servers::%loop-value%::players} is not 0:
				send "&8- &a%loop-value% &8({@color-2}%{_servers::%loop-value%::players}%&8)" to player
			else:
				send "&8- &a%loop-value% &8({@color-1}%{_servers::%loop-value%::players}%&8)" to player
		loop {_servers::*}:
			{_servers::%loop-value%::online} is false
			send "&8- &c%loop-value% {@color-1}&o(Offline)" to player
		send "&8&m                               " to player
```

**Comment by baylorhenshaw** [comment]
Here is the timings report.
https://timings.aikar.co/?id=b6cbf8d9c8894fdb9da689ef0820e34b
This only happens when I have the checking for the servers online mode and player counts on!

Also another part of the code for updating player counts and online mode.
```
# Online Mode & Player Count Checking
every 3 seconds:
	{@enable-server-updates} is true
	set {{@storage}::netPlayers} to number of players on network
	set {_servers::*} to {@server-list}
	loop {_servers::*}:
		if server loop-value is online:
			if {{@storage}::servers::%loop-value%::online} is false:
				{{@storage}::servers::%loop-value%::onlineCount} is 4
				set {{@storage}::servers::%loop-value%::online} to true
				{@enable-server-update-messages} is true
				broadcast "{@color-3}The server {@color-2}%loop-value%{@color-3} is now &aonline{@color-2}."
			add 1 to {{@storage}::servers::%loop-value%::onlineCount}
		else:
			if {{@storage}::servers::%loop-value%::online} is true:
				{@enable-server-update-messages} is true
				{{@storage}::servers::%loop-value%::onlineCount} is greater than 4
				broadcast "{@color-3}The server {@color-2}%loop-value%{@color-3} is now &coffline{@color-2}."
			set {{@storage}::servers::%loop-value%::online} to false
			delete {{@storage}::servers::%loop-value%::onlineCount}
		set {_online} to number of players on server loop-value
		if {_online} is not set:
			set {{@storage}::servers::%loop-value%::players} to 0
		else:
			set {{@storage}::servers::%loop-value%::players} to {_online}
		wait 3 tick
```

**Comment by scraft-official** [comment]
Okey, so for now, i found the main issue, which is the connection ping between BungeeCord and Server.
For now i will work on addon to make this events async, because the server wait until answer is set. If you need a quick fix, you can use MundoSK async system, which will help you a lot to make the addon work without problems. Example code with MundoSK for async:
```broadcast "Connecting to server!"
async
set {_online} to number of players on bungeecord server "hub1"
sync
broadcast "Number of players: %{_online}%"
```
If you can't find the working version of MundoSk, i have added it to this post, I hope it will help you until the version 1.4 will be released.
[MundoSK.zip](https://github.com/scraft-official/skScraft/files/5938738/MundoSK.zip)
Thank you for patient,
Scraft
