### ISSUE TITLE
Hexcolor-Support

### ISSUE THREAD

**Issue by ghost** [scraft-official/skScraft#4]
Hey!
Ur plugin doesnt support hexcolors, or i didnt find a way.
pls help

**Comment by scraft-official** [comment]
Hi,
Sorry for saying that, but i have some difficulites with implementation of HEXA colors to BungeeBridge, it's an old plugin. I have made some changes in it just to make it working for 1.14+, but adding a possibility of Hexa colors are not possible right now.
Best Regards,
Scraft
