### ISSUE TITLE
Conflicts between a skScraft and Skript expression

### ISSUE THREAD

**Issue by Vulqa** [scraft-official/skScraft#5]
## Description
I cannot retrieve the player's uuid via the player stocked in a variable, the {_uuid} variable give me "none"
I tested the expression by removing plugins one by one and it is actually a conflict with the skScraft's expression and the Skript's expression (this expression I think https://skripthub.net/docs/?id=4621 )

## Steps to Reproduce
Code :

```
command /test:
  trigger:
    test(player)

function test(player: player):
  set {_uuid} to uuid of {_player}
  message "%{_uuid}%" to {_player}
```
  
or

```
command /test:
  trigger:
    set {_player} to player
    set {_uuid} to uuid of {_player}
    message "%{_uuid}%"
```
    
## Server Information
Server version/platform: Paper 1.16.5
Skript version: 2.5.3
skScraft version: 1.3

**Comment by scraft-official** [comment]
Hi,
I think that the main reason why it's not working, is beacuse you used {_player} as player not as string and it will be better to use ``bungeecord uuid of``.
To make it working you should do something like this:
```set {_uuid} to bungeecord uuid of "%{_player}%"```
Also you need to remeber that the network uuid and local server uuid are not the same if you use ``offline mode``.
If you need any help, fell free to post your problem.
Best Regards,
Scraft

**Comment by Vulqa** [comment]
Thank you for the quick reply @scraft-official, In fact, I don't want to retrieve the player's uuid via bungeecord, I would just like to retrieve the uuid via the server with this expression (https://skripthub.net/docs/?id=923) but when the player target (which is not a String) is in the form of a variable it doesn't work because skScraft thinks I'm using his expression. It's quite annoying because if I want to get the uuid of a player in a function or elsewhere I can't, unless I use skript-reflect

**Comment by scraft-official** [comment]
Hi,
Sorry, i misunderstood you, I will upload totady an updated vesion with some features that i have added, and I will repair the uuid syntax.
Best Regards,
Scraft

**Comment by scraft-official** [comment]
Hi,
I have resolved this problem in the latest release. If you have any question/problems fell free to reopen this issue.
Best Regards,
Scraft
