### ISSUE TITLE
Expression to get the Bungee server that the script is running on.

### ISSUE THREAD

**Issue by Ryan12439** [scraft-official/skScraft#6]
Title pretty much says it all. We were using skungee but it proved extremely unreliable. We have skripts that run on start up that require it to know what bungee server it is.

**Comment by scraft-official** [comment]
Hi,
Thank you for this proposition, I have added it in the latest release. Now you can use:
```set {_name} to name of this server on bungeecord network```
Best Reagrds,
Scraft
