### ISSUE TITLE
Get all connected servers.

### ISSUE THREAD

**Issue by Blacksoul16** [scraft-official/skScraft#7]
Is it possible to add this feature? I find it strange to see that no one has asked for it, but it would make several things much easier, such as loops to get information from all servers more efficiently.

**Comment by scraft-official** [comment]
Hi,
I'm sorry but i have stopped developing this project. 

Still if you want this additional feature i would purpose you a work around by using Skript-DB and saving data to the database of active servers or by creating a name list of servers that you are using and checking for each if the player count is not null.
