### ISSUE TITLE
 Error occurred while enabling BungeeBridgeC v1.6.3 (Is it up to date?)

### ISSUE THREAD

**Issue by ghost** [scraft-official/skScraft#8]
Crash when using BungeeBridgeC v1.6.3 on minecraft 1.19.2.
[Log-file](https://github.com/scraft-official/skScraft/files/10100591/latest.2.log)

**Comment by ghost** [comment]
I will open this once the developer responds

**Comment by scraft-official** [comment]
Hi,
The problem is on BungeeBridge's end. The developer haven't updated the plugin to the newer versions of Minecraft, and I'am also no longer supporting skScraft, so I'm not planning to do it by myself.

I can purpose you to use BungeeSK, as it's being updated till these days.
Best regards,

**Comment by ghost** [comment]
BungeeSK hasn't gotten an update for a year but thank you for the advice. Though, I can use other plugins like SkWrapper or Skungee. **Thank you for your support!**
